#!/usr/bin/env python3
"""Generate the Home Assistant entity metadata catalog.

The generator intentionally parses ``adapter_metadata.py`` with ``ast`` instead
of importing Home Assistant. That keeps it usable in documentation-only
maintenance environments where the full HA runtime is not installed.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
METADATA_PATH = ROOT / "custom_components" / "idm_heatpump" / "adapter_metadata.py"
DOC_PATH = ROOT / "docs" / "dev" / "entity-metadata-catalog.md"


def _node_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        base = _node_name(node.value)
        return f"{base}.{node.attr}" if base else node.attr
    return ast.unparse(node)


def _node_value(node: ast.AST) -> Any:
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Attribute | ast.Name):
        return _node_name(node).split(".")[-1].lower()
    if isinstance(node, ast.Tuple | ast.List):
        return tuple(_node_value(item) for item in node.elts)
    if isinstance(node, ast.Dict):
        return {
            _node_value(key): _node_value(value)
            for key, value in zip(node.keys, node.values, strict=True)
            if key is not None
        }
    return ast.unparse(node)


def _module_assignments() -> dict[str, Any]:
    tree = ast.parse(METADATA_PATH.read_text(encoding="utf-8"), filename=str(METADATA_PATH))
    assignments: dict[str, Any] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign | ast.AnnAssign):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        for target in targets:
            if isinstance(target, ast.Name):
                assignments[target.id] = _node_value(node.value)
    return assignments


def _enabled(meta: dict[str, Any]) -> str:
    return "no" if meta.get("enabled_by_default") is False else "yes"


def _profile(meta: dict[str, Any]) -> str:
    if meta.get("enabled_by_default") is False:
        return "diagnostic_expert"
    if _category(meta) in {"diagnostic", "config"}:
        return "advanced"
    return "basic"


def _category(meta: dict[str, Any]) -> str:
    return str(meta.get("entity_category") or "main")


def _format_table(
    title: str,
    metadata: dict[str, dict[str, Any]],
    prefixes: tuple[str, ...],
    fragments: tuple[str, ...],
) -> list[str]:
    lines = [
        f"## {title}",
        "",
        "| Key | Name | Profile | Category | Enabled by default | Icon |",
        "|-----|------|---------|----------|--------------------|------|",
    ]
    for key in sorted(metadata):
        meta = metadata[key]
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{key}`",
                    str(meta.get("name") or "—"),
                    _profile(meta),
                    _category(meta),
                    _enabled(meta),
                    str(meta.get("icon") or "—"),
                )
            )
            + " |"
        )
    lines.append("")
    return lines


def _format_patterns(prefixes: tuple[str, ...], fragments: tuple[str, ...]) -> list[str]:
    lines = [
        "## Generated expert default profile",
        "",
        "Generated entities matching these prefixes or fragments are disabled by default unless explicit metadata keeps them enabled.",
        "",
        "### Prefixes",
        "",
    ]
    lines.extend(f"- `{item}`" for item in prefixes)
    lines.extend(["", "### Fragments", ""])
    lines.extend(f"- `{item}`" for item in fragments)
    lines.append("")
    return lines


def build_catalog() -> str:
    assignments = _module_assignments()
    sensor_metadata = assignments["SENSOR_METADATA"]
    number_metadata = assignments["NUMBER_METADATA"]
    prefixes = assignments["_EXPERT_DISABLED_PREFIXES"]
    fragments = assignments["_EXPERT_DISABLED_FRAGMENTS"]

    lines = [
        "# Entity Metadata Catalog",
        "",
        "> Generated by `python scripts/generate_entity_metadata_catalog.py`. Do not edit manually.",
        "",
        "This catalog documents the explicit Home Assistant metadata overlays and the conservative generated-entity default profile.",
        "",
    ]
    lines.extend(_format_table("Explicit sensor metadata", sensor_metadata, prefixes, fragments))
    lines.extend(_format_table("Explicit number metadata", number_metadata, prefixes, fragments))
    lines.extend(_format_patterns(prefixes, fragments))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the catalog is not up to date")
    args = parser.parse_args()

    generated = build_catalog()
    current = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""
    if args.check:
        if current != generated:
            raise SystemExit("Entity metadata catalog is not up to date")
        return 0
    DOC_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
