"""German display names for IDM Heatpump registers.

Extracted from library_adapter so the large translation table and zone-room
naming helpers live in a focused, pure-data module. The adapter imports
``_get_german_name`` from here.
"""

from __future__ import annotations

import re

_GERMAN_NAMES: dict[str, str] = {
    "outdoor_temp": "Außentemperatur",
    "outdoor_temp_avg": "Gemittelte Außentemperatur",
    "storage_temp": "Wärmespeichertemperatur",
    "cold_storage_temp": "Kältespeichertemperatur",
    "dhw_temp_bottom": "Trinkwassererwärmer unten",
    "dhw_temp_top": "Trinkwassererwärmer oben",
    "dhw_tapping_temp": "Warmwasser Zapftemperatur",
    "dhw_setpoint": "Warmwasser Sollwert",
    "hp_flow_temp": "Wärmepumpen Vorlauftemperatur",
    "hp_return_temp": "Wärmepumpen Rücklauftemperatur",
    "heat_source_inlet_temp": "Wärmequelleneintritt",
    "heat_source_outlet_temp": "Wärmequellenaustritt",
    "current_power": "Thermische Momentanleistung",
    "power_consumption_hp": "Elektrische Leistungsaufnahme Wärmepumpe",
    "evu_lock": "EVU Sperre",
    "hp_sum_alarm": "Summenstörung",
    "heat_sink_flow_rate": "Durchfluss Wärmesenke (B2)",
    "heat_sink_flow_temp": "Vorlauftemperatur Wärmesenke",
    "heat_sink_return_temp": "Rücklauftemperatur Wärmesenke",
    "heat_sink_charging_pump_signal": "Ladepumpe Wärmesenke",
    "charge_pump_status": "Ladepumpe",
    "brine_pump_status": "Sole-/Zwischenkreispumpe",
    "source_pump_status": "Wärmequellenpumpe",
    "isc_cold_pump_status": "ISC Kältespeicherpumpe",
    "isc_recool_pump_status": "ISC Rückkühlpumpe",
    "circulation_pump_status": "Zirkulationspumpe",
    "valve_hc_heat_cool": "Umschaltventil Heizkreis Heizen/Kühlen",
    "valve_storage_heat_cool": "Umschaltventil Speicher Heizen/Kühlen",
    "valve_heat_dhw": "Umschaltventil Heizen/Warmwasser",
    "solar_collector_temp": "Solar Kollektortemperatur",
    "solar_return_temp": "Solar Rücklauftemperatur",
    "solar_charging_temp": "Solar Ladetemperatur",
    "solar_mode": "Solar Betriebsart",
    "pv_surplus": "PV Überschuss",
    "pv_production": "PV Produktion",
    "house_consumption": "Hausverbrauch",
    "battery_discharge": "Batterie Entladung",
    "battery_soc": "Batterie SOC",
    "electric_heater_power": "E-Heizstab Leistung",
    "pv_target_value": "PV Zielwert",
    "variable_input": "Variabler Eingang",
    "cascade_available_heating": "Kaskade verfügbar Heizen",
    "cascade_available_cooling": "Kaskade verfügbar Kühlen",
    "cascade_available_dhw": "Kaskade verfügbar Warmwasser",
    "cascade_running_heating": "Kaskade in Betrieb Heizen",
    "cascade_running_cooling": "Kaskade in Betrieb Kühlen",
    "cascade_running_dhw": "Kaskade in Betrieb Warmwasser",
    "energy_heating": "Wärmemenge Heizen",
    "energy_cooling": "Wärmemenge Kühlen",
    "energy_dhw": "Wärmemenge Warmwasser",
    "energy_total": "Wärmemenge Gesamt",
    "energy_defrost": "Wärmemenge Abtauen",
    "energy_solar": "Wärmemenge Solar",
    "energy_electric_heater": "Wärmemenge E-Heizstab",
    "ext_outdoor_temp": "Externe Außentemperatur (GLT)",
    "ext_humidity": "Externe Feuchte (GLT)",
    "glt_temp_demand_heating": "GLT Temperaturanforderung Heizen",
    "glt_temp_demand_cooling": "GLT Temperaturanforderung Kühlen",
    "bivalence_state": "Bivalenz Betriebszustand",
    "smart_grid_status": "Smart Grid Status",
    "internal_message": "Interne Meldung",
    "hp_operating_mode": "Wärmepumpen Betriebsart",
    "heating_demand": "Heizanforderung",
    "cooling_demand": "Kühlanforderung",
    "dhw_demand": "Warmwasseranforderung",
    "compressor_status_1": "Verdichter 1",
    "compressor_status_2": "Verdichter 2",
    "compressor_status_3": "Verdichter 3",
    "compressor_status_4": "Verdichter 4",
    "valve_solar_heat_dhw": "Solar Umschaltventil Heizen/WW",
    "valve_heat_source_heat_cool": "Wärmequelle Umschaltventil",
    "bivalence_point_1_2nd_gen": "Bivalenzpunkt 1 (2. WE)",
    "bivalence_point_2_2nd_gen": "Bivalenzpunkt 2 (2. WE)",
    "glt_heat_storage_temp": "GLT Wärmespeichertemperatur",
    "glt_cold_storage_temp": "GLT Kältespeichertemperatur",
    "glt_dhw_temp_bottom": "GLT Warmwasser unten",
    "glt_dhw_temp_top": "GLT Warmwasser oben",
    "demand_heating": "Externe Heizanforderung",
    "demand_cooling": "Externe Kühlanforderung",
    "demand_dhw_charging": "Externe WW-Ladeanforderung",
    "total_heat_energy": "Gesamte Wärmemenge (Vortex)",
    "thermal_power_flow_sensor": "Thermische Leistung (Durchflusssensor)",
    "air_intake_temp": "Luftansaugtemperatur",
    "air_heat_exchanger_temp": "Luftwärmetauscher Temperatur",
    "charging_sensor_temp": "Ladefühler Temperatur",
    "ext_demand_temp_heating": "Externe Anforderungstemperatur Heizen",
    "ext_demand_temp_cooling": "Externe Anforderungstemperatur Kühlen",
    "air_intake_temp_2": "Luftansaugtemperatur 2",
    "valve_solar_storage_heat_source": "Solar Speicher/Wärmequelle Ventil",
    "valve_isc_heat_source_cold_storage": "ISC Umschaltventil",
    "valve_isc_storage_bypass": "Umschaltventil ISC Speicher/Bypass",
    "isc_charging_temp_cooling": "ISC Ladetemperatur Kühlen",
    "isc_recooling_temp": "ISC Rückkühltemperatur",
    "isc_mode": "ISC Modus",
    "ext_room_temp": "Externe Raumtemperatur",
    "humidity_sensor": "Feuchtesensor",
    "fault_heat_source_circuit": "Störung Wärmequellenkreis",
    "fault_heat_source_pressure": "Störung Druckschalter Wärmequelle",
    "booster_a_source_inlet_temp": "Booster A Wärmequelleneintritt",
    "booster_a_flow_temp": "Booster A Vorlauftemperatur",
    "booster_a_compressor": "Booster A Verdichter",
    "booster_b_compressor": "Booster B Verdichter",
    "power_limit_hp": "Leistungsbegrenzung Wärmepumpe",
    "power_limit_cascade": "Leistungsbegrenzung Kaskade",
    "dhw_draw_temp": "Warmwasserzapftemperatur",
    "current_energy_price": "Aktueller Strompreis",
    "hgl_flow_temp": "HGL Vorlauftemperatur B35",
    "air_hx_temp": "Luftwärmetauschertemperatur B72",
    "charge_sensor_temp": "Ladefühler B45",
    "heatpump_status": "Betriebsart Wärmepumpe",
    "valve_source_heat_cool": "Umschaltventil Wärmequelle Heizen/Kühlen",
    "valve_solar_storage_source": "Umschaltventil Solar Speicher/Wärmequelle",
    "valve_isc_source_cold": "Umschaltventil ISC Wärmequelle/Kältespeicher",
    "cascade_avail_stages_heat": "Kaskade Verfügbare Stufen Heizen",
    "cascade_avail_stages_cool": "Kaskade Verfügbare Stufen Kühlen",
    "cascade_avail_stages_dhw": "Kaskade Verfügbare Stufen Warmwasser",
    "cascade_running_stages_heat": "Kaskade Laufende Stufen Heizen",
    "cascade_running_stages_cool": "Kaskade Laufende Stufen Kühlen",
    "cascade_running_stages_dhw": "Kaskade Laufende Stufen Warmwasser",
    "cascade_req_heat_temp": "Kaskade Angeforderte Heiztemperatur",
    "cascade_req_cool_temp": "Kaskade Angeforderte Kühltemperatur",
    "cascade_req_dhw_temp": "Kaskade Angeforderte WW-Temperatur",
    "cascade_avg_flow_heat": "Kaskade Gemittelte VL-Temp Heizen",
    "cascade_avg_flow_cool": "Kaskade Gemittelte VL-Temp Kühlen",
    "cascade_avg_flow_dhw": "Kaskade Gemittelte VL-Temp Warmwasser",
    "humidity": "Feuchtesensor",
    "outdoor_temp_ext": "Externe Außentemperatur",
    "humidity_ext": "Externe Feuchte",
    "energy_heat_heating": "Wärmemenge Heizen",
    "energy_heat_total": "Wärmemenge Gesamt",
    "energy_heat_cooling": "Wärmemenge Kühlen",
    "energy_heat_dhw": "Wärmemenge Warmwasser",
    "energy_heat_defrost": "Wärmemenge Abtauung",
    "energy_heat_passive_cooling": "Wärmemenge Passive Kühlen",
    "energy_heat_solar": "Wärmemenge Solar",
    "energy_heat_electric": "Wärmemenge Elektroheizeinsatz",
    "current_power_draw": "Momentanleistung",
    "solar_collector_return_temp": "Solar Kollektorrücklauftemperatur",
    "solar_charge_temp": "Solar Ladetemperatur",
    "solar_reference_temp": "Solar WQ-Referenztemperatur/Pooltemperatur",
    "isc_charge_cooling_temp": "ISC Ladetemperatur Kühlen",
    "firmware_version": "Firmware Version Navigator",
    "power_draw_total": "Aktuelle Leistungsaufnahme Wärmepumpe",
    "thermal_power": "Thermische Leistung",
    "energy_total_flow_sensor": "Wärmemenge Gesamt (Durchflusssensor)",
    "flow_temp_hk": "Vorlauftemperatur Heizkreis",
    "room_temp_hk": "Raumtemperatur Heizkreis",
    "target_flow_temp_hk": "Sollvorlauftemperatur Heizkreis",
    "room_target_heat_normal": "Raumsoll Heizen Normal",
    "room_target_heat_eco": "Raumsoll Heizen Eco",
    "room_target_cool_normal": "Raumsoll Kühlen Normal",
    "room_target_cool_eco": "Raumsoll Kühlen Eco",
    "heating_curve": "Heizkurve",
    "heating_limit": "Heizgrenze",
    "cooling_limit": "Kühlgrenze",
    "parallel_shift": "Parallelverschiebung",
    "active_mode": "Aktive Betriebsart",
    "zone_mode": "Zonenmodus",
    "zone_room_temp": "Raumtemperatur Zone",
    "zone_room_target": "Raumsolltemperatur Zone",
    "zone_room_humidity": "Raumfeuchte Zone",
    "zone_room_mode": "Raumbetriebsart Zone",
    # === System mode ===
    "system_mode": "Systembetriebsart",
    "error_acknowledge": "Fehlerquittierung",
    # === Booster detailed ===
    "booster_a_charging_pump": "Booster A Ladepumpe",
    "booster_a_return_temp": "Booster A Rücklauftemperatur",
    "booster_a_source_outlet_temp": "Booster A Wärmequellenaustritt",
    "booster_a_source_pump": "Booster A Wärmequellenpumpe",
    "booster_a_storage_temp": "Booster A Speichertemperatur",
    "booster_b_charging_pump": "Booster B Ladepumpe",
    "booster_b_flow_temp": "Booster B Vorlauftemperatur",
    "booster_b_return_temp": "Booster B Rücklauftemperatur",
    "booster_b_source_inlet_temp": "Booster B Wärmequelleneintritt",
    "booster_b_source_outlet_temp": "Booster B Wärmequellenaustritt",
    "booster_b_source_pump": "Booster B Wärmequellenpumpe",
    "booster_b_storage_temp": "Booster B Speichertemperatur",
    "booster_interlock": "Booster Verriegelung",
    # === Pumpen ===
    "charging_pump_status": "Ladepumpe M73",
    "heat_source_pump_status": "Wärmequellenpumpe M15",
    "circulation_pump": "Zirkulationspumpe M64",
    "isc_cold_storage_pump_status": "ISC Kältespeicherpumpe M84",
    "isc_recooling_pump_status": "ISC Rückkühlpumpe M17",
    # === DHW detail ===
    "dhw_charge_on_temp": "WW Einchargetemperatur",
    "dhw_charge_off_temp": "WW Ausschalttemperatur",
    "current_electricity_price": "Aktueller Strompreis",
    "current_power_solar": "Aktuelle Solarleistung",
    "energy_passive_cooling": "Wärmemenge Passive Kühlung",
    # === Bivalenz 3. Gen ===
    "bivalence_point_1_3rd_gen": "Bivalenzpunkt 1 (3. WE)",
    "bivalence_point_2_3rd_gen": "Bivalenzpunkt 2 (3. WE)",
    # === Fehler / Diagnose ===
    "fault_heat_source_pressure_switch": "Störung Druckschalter Wärmequellenkreis",
    "fault_charging_pump_1_intermediate": "Störung Ladepumpe 1 Zwischenkreis",
    "fault_charging_pump_2_intermediate": "Störung Ladepumpe 2 Zwischenkreis",
    # === Grundwasser ===
    "groundwater_inlet_temp_1": "Grundwassereintrittstemperatur 1",
    "groundwater_inlet_temp_2": "Grundwassereintrittstemperatur 2",
    # === GLT / Extern ===
    "ext_demand_groundwater_pump_m15": "Externe Anforderung Grundwasserpumpe M15",
    "ext_demand_groundwater_pump_m15_sw_max": "Externe Anforderung Grundwasserpumpe M15 (SW max)",
    "demand_onetime_dhw": "Einmalige WW-Anforderung",
    "power_consumption_hp_smartfox": "Elektrische Leistungsaufnahme Smartfox",
    # === Heizkreis A ===
    "hc_a_flow_temp": "Vorlauftemperatur HK A",
    "hc_a_room_temp": "Raumtemperatur HK A",
    "hc_a_setpoint_flow_temp": "Sollvorlauftemperatur HK A",
    "hc_a_active_mode": "Aktive Betriebsart HK A",
    "hc_a_mode": "Betriebsart HK A",
    "hc_a_room_setpoint_heat_normal": "Raumsoll Heizen Normal HK A",
    "hc_a_room_setpoint_heat_eco": "Raumsoll Heizen Eco HK A",
    "hc_a_room_setpoint_cool_normal": "Raumsoll Kühlen Normal HK A",
    "hc_a_room_setpoint_cool_eco": "Raumsoll Kühlen Eco HK A",
    "hc_a_heating_curve": "Heizkurve HK A",
    "hc_a_heating_limit": "Heizgrenze HK A",
    "hc_a_cooling_limit": "Kühlgrenze HK A",
    "hc_a_setpoint_flow_constant": "Festwertvorlauf HK A",
    "hc_a_setpoint_flow_cooling": "Kühlvorlauf HK A",
    "hc_a_parallel_shift": "Parallelverschiebung HK A",
    "hc_a_ext_room_temp": "Externe Raumtemperatur HK A",
    # === Kaskade Detail ===
    "cascade_req_heating_temp": "Kaskade Angeforderte Heiztemperatur",
    "cascade_req_cooling_temp": "Kaskade Angeforderte Kühltemperatur",
    "cascade_avg_flow_heating": "Kaskade Gemittelte VL-Temp Heizen",
    "cascade_avg_flow_cooling": "Kaskade Gemittelte VL-Temp Kühlen",
    "cascade_min_power_heating": "Kaskade Mindestleistung Heizen",
    "cascade_min_power_cooling": "Kaskade Mindestleistung Kühlen",
    "cascade_min_power_dhw": "Kaskade Mindestleistung Warmwasser",
    "cascade_max_power_heating": "Kaskade Maximalleistung Heizen",
    "cascade_max_power_cooling": "Kaskade Maximalleistung Kühlen",
    "cascade_max_power_dhw": "Kaskade Maximalleistung Warmwasser",
    "cascade_bivalence_heating_parallel": "Kaskade Bivalenz Heizen Parallel",
    "cascade_bivalence_heating_alternative": "Kaskade Bivalenz Heizen Alternativ",
    "cascade_bivalence_cooling_parallel": "Kaskade Bivalenz Kühlen Parallel",
    "cascade_bivalence_cooling_alternative": "Kaskade Bivalenz Kühlen Alternativ",
    "cascade_bivalence_dhw_parallel": "Kaskade Bivalenz WW Parallel",
    "cascade_bivalence_dhw_alternative": "Kaskade Bivalenz WW Alternativ",
    # === Solar Detail ===
    "solar_wq_pool_temp": "Solar WQ-Referenztemperatur/Pooltemperatur",
    # === Booster (bereits teilweise vorhanden) ===
    "booster_fault": "Booster Störung",
}


_ZONE_ROOM_NAME_RE = re.compile(r"zm(\d+)_room(\d+)_(temp|setpoint|humidity|mode|relay)$")

_ZONE_ROOM_NAME_SUFFIX: dict[str, str] = {
    "temp": "Raumtemperatur",
    "setpoint": "Raumsolltemperatur",
    "humidity": "Raumfeuchte",
    "mode": "Raumbetriebsart",
    "relay": "Relais",
}


def _get_german_name(name: str) -> str:
    """Liefert einen schönen deutschen Namen, falls bekannt, sonst eine formatierte Version."""
    if name in _GERMAN_NAMES:
        return _GERMAN_NAMES[name]
    zone_match = _ZONE_ROOM_NAME_RE.match(name)
    if zone_match:
        zone, room, kind = zone_match.groups()
        return f"Zone {zone} Raum {room} {_ZONE_ROOM_NAME_SUFFIX[kind]}"
    return name.replace("_", " ").title()
