name: Hassfest Validation

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  release:
    types: [published, prereleased]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    name: Hassfest Action
    steps:
      - uses: actions/checkout@v4
      - name: Hassfest Action
        uses: home-assistant/actions/hassfest@master
